In [1]:
# Imports
import pandas as pd
import numpy as np
import csv

In [2]:
# Load in CSV files
file_path = 'Resources/Conditions_Contributing_to_COVID-19_Deaths__by_State_and_Age__Provisional_2020-2022.csv'
Covid_contributing_conditions = pd.read_csv(file_path)
Covid_contributing_conditions

,Data As Of,Start Date,End Date,Group,Year,Month,State,Condition Group,Condition,ICD10_codes,Age Group,COVID-19 Deaths,Number of Mentions,Flag
0,05/01/2022,01/01/2020,04/30/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,0-24,1320.0,1380.0,NaN
1,05/01/2022,01/01/2020,04/30/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,25-34,5483.0,5685.0,NaN
2,05/01/2022,01/01/2020,04/30/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,35-44,14389.0,14967.0,NaN
3,05/01/2022,01/01/2020,04/30/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,45-54,35815.0,37186.0,NaN
4,05/01/2022,01/01/2020,04/30/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,55-64,78488.0,81289.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397435,05/01/2022,12/01/2021,12/31/2021,By Month,2021.0,12.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,54.0,54.0,NaN
397436,05/01/2022,01/01/2022,01/31/2022,By Month,2022.0,1.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,621.0,621.0,NaN
397437,05/01/2022,02/01/2022,02/28/2022,By Month,2022.0,2.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,209.0,209.0,NaN
397438,05/01/2022,03/01/2022,03/31/2022,By Month,2022.0,3.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,47.0,47.0,NaN
397439,05/01/2022,04/01/2022,04/30/2022,By Month,2022.0,4.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,23.0,23.0,NaN

In [3]:
Covid_contributing_conditions.columns.tolist()

['Data As Of',
 'Start Date',
 'End Date',
 'Group',
 'Year',
 'Month',
 'State',
 'Condition Group',
 'Condition',
 'ICD10_codes',
 'Age Group',
 'COVID-19 Deaths',
 'Number of Mentions',
 'Flag']

In [4]:
# Create a DataFrame object
Covid_contributing_conditions_df = pd.DataFrame(Covid_contributing_conditions, columns= ['State', 'Condition Group', 'Condition', 'ICD10_codes', 'Age Group', 'COVID-19 Deaths'])

In [6]:
print(Covid_contributing_conditions_df)

                State       Condition Group                Condition  \
0       United States  Respiratory diseases  Influenza and pneumonia
1       United States  Respiratory diseases  Influenza and pneumonia
2       United States  Respiratory diseases  Influenza and pneumonia
3       United States  Respiratory diseases  Influenza and pneumonia
4       United States  Respiratory diseases  Influenza and pneumonia
...               ...                   ...                      ...
397435    Puerto Rico              COVID-19                 COVID-19
397436    Puerto Rico              COVID-19                 COVID-19
397437    Puerto Rico              COVID-19                 COVID-19
397438    Puerto Rico              COVID-19                 COVID-19
397439    Puerto Rico              COVID-19                 COVID-19

       ICD10_codes Age Group  COVID-19 Deaths
0          J09-J18      0-24           1320.0
1          J09-J18     25-34           5483.0
2          J09-J18     35-44          14389.0
3          J09-J18     45-54          35815.0
4          J09-J18     55-64          78488.0
...            ...       ...              ...
397435        U071  All Ages             54.0
397436        U071  All Ages            621.0
397437        U071  All Ages            209.0
397438        U071  All Ages             47.0
397439        U071  All Ages             23.0

[397440 rows x 6 columns]

In [7]:
# Get a series of unique values in column 'Condition' of the dataframe
uniqueValues = Covid_contributing_conditions_df['Condition Group'].unique()
print('Unique elements in column "Condition Group" ')
print(uniqueValues)

Unique elements in column "Condition Group"
['Respiratory diseases' 'Circulatory diseases' 'Sepsis'
 'Malignant neoplasms' 'Diabetes' 'Obesity' 'Alzheimer disease'
 'Vascular and unspecified dementia' 'Renal failure'
 'Intentional and unintentional injury, poisoning, and other adverse events'
 'All other conditions and causes (residual)' 'COVID-19']

In [8]:
# Get a series of unique values in column 'Age Group' of the dataframe
uniqueValues = Covid_contributing_conditions_df['Age Group'].unique()
print('Unique elements in column "Age Group" ')
print(uniqueValues)

Unique elements in column "Age Group"
['0-24' '25-34' '35-44' '45-54' '55-64' '65-74' '75-84' '85+' 'Not stated'
 'All Ages']