In [1]:
# Imports
import pandas as pd
import numpy as np
import csv

In [2]:
# Load in CSV files
file_path = 'Resources/Covid-19/Data/Conditions_Contributing_to_COVID-19_Deaths__by_State_and_Age__Provisional_2020-2022.csv'
Covid_contributing_conditions = pd.read_csv(file_path)
Covid_contributing_conditions

,Data As Of,Start Date,End Date,Group,Year,Month,State,Condition Group,Condition,ICD10_codes,Age Group,COVID-19 Deaths,Number of Mentions,Flag
0,05/08/2022,01/01/2020,05/07/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,0-24,1321.0,1381.0,NaN
1,05/08/2022,01/01/2020,05/07/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,25-34,5492.0,5694.0,NaN
2,05/08/2022,01/01/2020,05/07/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,35-44,14410.0,14989.0,NaN
3,05/08/2022,01/01/2020,05/07/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,45-54,35873.0,37250.0,NaN
4,05/08/2022,01/01/2020,05/07/2022,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,55-64,78619.0,81430.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409855,05/08/2022,01/01/2022,01/31/2022,By Month,2022.0,1.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,621.0,621.0,NaN
409856,05/08/2022,02/01/2022,02/28/2022,By Month,2022.0,2.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,209.0,209.0,NaN
409857,05/08/2022,03/01/2022,03/31/2022,By Month,2022.0,3.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,47.0,47.0,NaN
409858,05/08/2022,04/01/2022,04/30/2022,By Month,2022.0,4.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,31.0,31.0,NaN
409859,05/08/2022,05/01/2022,05/07/2022,By Month,2022.0,5.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,NaN,NaN,One or more data cells have counts between 1-9...

In [3]:
Covid_contributing_conditions.columns.tolist()

['Data As Of',
 'Start Date',
 'End Date',
 'Group',
 'Year',
 'Month',
 'State',
 'Condition Group',
 'Condition',
 'ICD10_codes',
 'Age Group',
 'COVID-19 Deaths',
 'Number of Mentions',
 'Flag']

In [4]:
Covid_contributing_conditions_monthly = Covid_contributing_conditions.loc[Covid_contributing_conditions['Group'] == 'By Month']

In [5]:
Covid_contributing_conditions_monthly = Covid_contributing_conditions_monthly.drop(columns=['Flag', 'Data As Of', 'End Date', 'Group', 'Year', 'Month', 'ICD10_codes'])

In [6]:
Covid_contributing_conditions_monthly

,Start Date,State,Condition Group,Condition,Age Group,COVID-19 Deaths,Number of Mentions
49680,01/01/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0,0.0
49681,02/01/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0,0.0
49682,03/01/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,9.0,9.0
49683,04/01/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,27.0,30.0
49684,05/01/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,19.0,19.0
...,...,...,...,...,...,...,...
409855,01/01/2022,Puerto Rico,COVID-19,COVID-19,All Ages,621.0,621.0
409856,02/01/2022,Puerto Rico,COVID-19,COVID-19,All Ages,209.0,209.0
409857,03/01/2022,Puerto Rico,COVID-19,COVID-19,All Ages,47.0,47.0
409858,04/01/2022,Puerto Rico,COVID-19,COVID-19,All Ages,31.0,31.0
409859,05/01/2022,Puerto Rico,COVID-19,COVID-19,All Ages,NaN,NaN

In [7]:
Covid_contributing_conditions_monthly['Start Date'] = pd.to_datetime(Covid_contributing_conditions_monthly['Start Date'])

In [8]:
Covid_contributing_conditions_monthly= Covid_contributing_conditions_monthly.drop(columns='Number of Mentions')

In [9]:
Covid_contributing_conditions_monthly

,Start Date,State,Condition Group,Condition,Age Group,COVID-19 Deaths
49680,2020-01-01,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0
49681,2020-02-01,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0
49682,2020-03-01,United States,Respiratory diseases,Influenza and pneumonia,0-24,9.0
49683,2020-04-01,United States,Respiratory diseases,Influenza and pneumonia,0-24,27.0
49684,2020-05-01,United States,Respiratory diseases,Influenza and pneumonia,0-24,19.0
...,...,...,...,...,...,...
409855,2022-01-01,Puerto Rico,COVID-19,COVID-19,All Ages,621.0
409856,2022-02-01,Puerto Rico,COVID-19,COVID-19,All Ages,209.0
409857,2022-03-01,Puerto Rico,COVID-19,COVID-19,All Ages,47.0
409858,2022-04-01,Puerto Rico,COVID-19,COVID-19,All Ages,31.0
409859,2022-05-01,Puerto Rico,COVID-19,COVID-19,All Ages,NaN

In [10]:
Covid_contributing_conditions_monthly['Start Date'] = Covid_contributing_conditions_monthly['Start Date'].dt.strftime('%m/%Y')

In [11]:
Covid_contributing_conditions_monthly

,Start Date,State,Condition Group,Condition,Age Group,COVID-19 Deaths
49680,01/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0
49681,02/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0
49682,03/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,9.0
49683,04/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,27.0
49684,05/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,19.0
...,...,...,...,...,...,...
409855,01/2022,Puerto Rico,COVID-19,COVID-19,All Ages,621.0
409856,02/2022,Puerto Rico,COVID-19,COVID-19,All Ages,209.0
409857,03/2022,Puerto Rico,COVID-19,COVID-19,All Ages,47.0
409858,04/2022,Puerto Rico,COVID-19,COVID-19,All Ages,31.0
409859,05/2022,Puerto Rico,COVID-19,COVID-19,All Ages,NaN

In [12]:
Covid_contributing_conditions_monthly = Covid_contributing_conditions_monthly.dropna()

In [13]:
Covid_contributing_conditions_monthly

,Start Date,State,Condition Group,Condition,Age Group,COVID-19 Deaths
49680,01/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0
49681,02/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0
49682,03/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,9.0
49683,04/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,27.0
49684,05/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,19.0
...,...,...,...,...,...,...
409854,12/2021,Puerto Rico,COVID-19,COVID-19,All Ages,54.0
409855,01/2022,Puerto Rico,COVID-19,COVID-19,All Ages,621.0
409856,02/2022,Puerto Rico,COVID-19,COVID-19,All Ages,209.0
409857,03/2022,Puerto Rico,COVID-19,COVID-19,All Ages,47.0
409858,04/2022,Puerto Rico,COVID-19,COVID-19,All Ages,31.0

In [14]:
Covid_contributing_conditions_monthly = Covid_contributing_conditions_monthly.reset_index()

In [15]:
Covid_contributing_conditions_monthly = Covid_contributing_conditions_monthly.drop(columns=['index'])

In [16]:
Covid_contributing_conditions_monthly = Covid_contributing_conditions_monthly.rename(columns= {'Start Date':'Month',
                                                                                              'Condition Group': 'Condition_Group',
                                                                                              'Age Group': 'Age_Group',
                                                                                              'COVID-19 Deaths': 'COVID-19_Deaths'})

In [17]:
Covid_contributing_conditions_monthly

,Month,State,Condition_Group,Condition,Age_Group,COVID-19_Deaths
0,01/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0
1,02/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,0.0
2,03/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,9.0
3,04/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,27.0
4,05/2020,United States,Respiratory diseases,Influenza and pneumonia,0-24,19.0
...,...,...,...,...,...,...
256333,12/2021,Puerto Rico,COVID-19,COVID-19,All Ages,54.0
256334,01/2022,Puerto Rico,COVID-19,COVID-19,All Ages,621.0
256335,02/2022,Puerto Rico,COVID-19,COVID-19,All Ages,209.0
256336,03/2022,Puerto Rico,COVID-19,COVID-19,All Ages,47.0
256337,04/2022,Puerto Rico,COVID-19,COVID-19,All Ages,31.0

In [18]:
Covid_contributing_conditions_monthly = Covid_contributing_conditions_monthly.astype({'COVID-19_Deaths': 'int32'}).dtypes

In [19]:
file_path = 'Resources/Covid-19/Cleaned_Data/Covid_contributing_conditions_monthly.csv'
Covid_contributing_conditions_monthly.to_csv(file_path)